//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService", ConfigurationName="ChequeDispenseServicePort")]
public interface ChequeDispenseServicePort
{
    
    // CODEGEN: Generating message contract since the operation GetTransactionID is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetTransactionIDResponse1 GetTransactionID(GetTransactionIDRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<GetTransactionIDResponse1> GetTransactionIDAsync(GetTransactionIDRequest1 request);
    
    // CODEGEN: Generating message contract since the operation PrintedBooklet is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    PrintedBookletResponse1 PrintedBooklet(PrintedBookletRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<PrintedBookletResponse1> PrintedBookletAsync(PrintedBookletRequest1 request);
    
    // CODEGEN: Generating message contract since the operation ValidateTransactionID is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ValidateTransactionIDResponse1 ValidateTransactionID(ValidateTransactionIDRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ValidateTransactionIDResponse1> ValidateTransactionIDAsync(ValidateTransactionIDRequest1 request);
    
    // CODEGEN: Generating message contract since the operation GetBookletDetails is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetBookletDetailsResponse1 GetBookletDetails(GetBookletDetailsRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<GetBookletDetailsResponse1> GetBookletDetailsAsync(GetBookletDetailsRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class GetTransactionIDRequest
{
    
    private TransactionIDDetailsRequestDTO detailsRequestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public TransactionIDDetailsRequestDTO DetailsRequest
    {
        get
        {
            return this.detailsRequestField;
        }
        set
        {
            this.detailsRequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class TransactionIDDetailsRequestDTO
{
    
    private string cardMagData1Field;
    
    private string cardMagData2Field;
    
    private string cardMagData3Field;
    
    private string encryptedPinBlockField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string CardMagData1
    {
        get
        {
            return this.cardMagData1Field;
        }
        set
        {
            this.cardMagData1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string CardMagData2
    {
        get
        {
            return this.cardMagData2Field;
        }
        set
        {
            this.cardMagData2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string CardMagData3
    {
        get
        {
            return this.cardMagData3Field;
        }
        set
        {
            this.cardMagData3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string EncryptedPinBlock
    {
        get
        {
            return this.encryptedPinBlockField;
        }
        set
        {
            this.encryptedPinBlockField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class BookletDetailsResponseDTO
{
    
    private string transactionStatusField;
    
    private string transactionIDField;
    
    private string accountNumberField;
    
    private string bookletRequestField;
    
    private string serialFromField;
    
    private string serialToField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string TransactionStatus
    {
        get
        {
            return this.transactionStatusField;
        }
        set
        {
            this.transactionStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string AccountNumber
    {
        get
        {
            return this.accountNumberField;
        }
        set
        {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string BookletRequest
    {
        get
        {
            return this.bookletRequestField;
        }
        set
        {
            this.bookletRequestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string SerialFrom
    {
        get
        {
            return this.serialFromField;
        }
        set
        {
            this.serialFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string SerialTo
    {
        get
        {
            return this.serialToField;
        }
        set
        {
            this.serialToField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class BookletDetailsRequestDTO
{
    
    private string accountField;
    
    private string transactionStatusField;
    
    private string transactionIDField;
    
    private string otpField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Account
    {
        get
        {
            return this.accountField;
        }
        set
        {
            this.accountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string TransactionStatus
    {
        get
        {
            return this.transactionStatusField;
        }
        set
        {
            this.transactionStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Otp
    {
        get
        {
            return this.otpField;
        }
        set
        {
            this.otpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class ValidateTransactionIDResponseDTO
{
    
    private string transactionIDField;
    
    private string transactionStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string TransactionStatus
    {
        get
        {
            return this.transactionStatusField;
        }
        set
        {
            this.transactionStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class ValidateTransactionIDRequestDTO
{
    
    private string transactionIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class PrintChequeDispenseResponseDTO
{
    
    private string transactionStatusField;
    
    private string transactionIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string TransactionStatus
    {
        get
        {
            return this.transactionStatusField;
        }
        set
        {
            this.transactionStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class PrintChequeDispenseRequestDTO
{
    
    private string transactionStatusField;
    
    private string transactionIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string TransactionStatus
    {
        get
        {
            return this.transactionStatusField;
        }
        set
        {
            this.transactionStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class ErrorDTO
{
    
    private string errorCodeField;
    
    private string errorDescField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string errorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string errorDesc
    {
        get
        {
            return this.errorDescField;
        }
        set
        {
            this.errorDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class TransactionIDDetailsResponseDTO
{
    
    private string transactionStatusField;
    
    private int numberOfAccountsField;
    
    private string[] accountsField;
    
    private string transactionIDField;
    
    private ErrorDTO errorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string TransactionStatus
    {
        get
        {
            return this.transactionStatusField;
        }
        set
        {
            this.transactionStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int NumberOfAccounts
    {
        get
        {
            return this.numberOfAccountsField;
        }
        set
        {
            this.numberOfAccountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Accounts", IsNullable=true, Order=2)]
    public string[] Accounts
    {
        get
        {
            return this.accountsField;
        }
        set
        {
            this.accountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public ErrorDTO Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class GetTransactionIDResponse
{
    
    private TransactionIDDetailsResponseDTO detailsResponseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public TransactionIDDetailsResponseDTO DetailsResponse
    {
        get
        {
            return this.detailsResponseField;
        }
        set
        {
            this.detailsResponseField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetTransactionIDRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService", Order=0)]
    public GetTransactionIDRequest GetTransactionIDRequest;
    
    public GetTransactionIDRequest1()
    {
    }
    
    public GetTransactionIDRequest1(GetTransactionIDRequest GetTransactionIDRequest)
    {
        this.GetTransactionIDRequest = GetTransactionIDRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetTransactionIDResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService", Order=0)]
    public GetTransactionIDResponse GetTransactionIDResponse;
    
    public GetTransactionIDResponse1()
    {
    }
    
    public GetTransactionIDResponse1(GetTransactionIDResponse GetTransactionIDResponse)
    {
        this.GetTransactionIDResponse = GetTransactionIDResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class PrintedBookletRequest
{
    
    private PrintChequeDispenseRequestDTO printChequeDispenseRequestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public PrintChequeDispenseRequestDTO PrintChequeDispenseRequest
    {
        get
        {
            return this.printChequeDispenseRequestField;
        }
        set
        {
            this.printChequeDispenseRequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class PrintedBookletResponse
{
    
    private PrintChequeDispenseResponseDTO printChequeDispenseResponseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public PrintChequeDispenseResponseDTO PrintChequeDispenseResponse
    {
        get
        {
            return this.printChequeDispenseResponseField;
        }
        set
        {
            this.printChequeDispenseResponseField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class PrintedBookletRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService", Order=0)]
    public PrintedBookletRequest PrintedBookletRequest;
    
    public PrintedBookletRequest1()
    {
    }
    
    public PrintedBookletRequest1(PrintedBookletRequest PrintedBookletRequest)
    {
        this.PrintedBookletRequest = PrintedBookletRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class PrintedBookletResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService", Order=0)]
    public PrintedBookletResponse PrintedBookletResponse;
    
    public PrintedBookletResponse1()
    {
    }
    
    public PrintedBookletResponse1(PrintedBookletResponse PrintedBookletResponse)
    {
        this.PrintedBookletResponse = PrintedBookletResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class ValidateTransactionIDRequest
{
    
    private ValidateTransactionIDRequestDTO transactionDetailsRequestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ValidateTransactionIDRequestDTO TransactionDetailsRequest
    {
        get
        {
            return this.transactionDetailsRequestField;
        }
        set
        {
            this.transactionDetailsRequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class ValidateTransactionIDResponse
{
    
    private ValidateTransactionIDResponseDTO transactionDetailsResponseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ValidateTransactionIDResponseDTO TransactionDetailsResponse
    {
        get
        {
            return this.transactionDetailsResponseField;
        }
        set
        {
            this.transactionDetailsResponseField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ValidateTransactionIDRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService", Order=0)]
    public ValidateTransactionIDRequest ValidateTransactionIDRequest;
    
    public ValidateTransactionIDRequest1()
    {
    }
    
    public ValidateTransactionIDRequest1(ValidateTransactionIDRequest ValidateTransactionIDRequest)
    {
        this.ValidateTransactionIDRequest = ValidateTransactionIDRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ValidateTransactionIDResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService", Order=0)]
    public ValidateTransactionIDResponse ValidateTransactionIDResponse;
    
    public ValidateTransactionIDResponse1()
    {
    }
    
    public ValidateTransactionIDResponse1(ValidateTransactionIDResponse ValidateTransactionIDResponse)
    {
        this.ValidateTransactionIDResponse = ValidateTransactionIDResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class GetBookletDetailsRequest
{
    
    private BookletDetailsRequestDTO bookletDetailsRequestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public BookletDetailsRequestDTO BookletDetailsRequest
    {
        get
        {
            return this.bookletDetailsRequestField;
        }
        set
        {
            this.bookletDetailsRequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wstutorial.com/ws/ChequeDispenseService")]
public partial class GetBookletDetailsResponse
{
    
    private BookletDetailsResponseDTO bookletDetailsResponseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public BookletDetailsResponseDTO BookletDetailsResponse
    {
        get
        {
            return this.bookletDetailsResponseField;
        }
        set
        {
            this.bookletDetailsResponseField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetBookletDetailsRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService", Order=0)]
    public GetBookletDetailsRequest GetBookletDetailsRequest;
    
    public GetBookletDetailsRequest1()
    {
    }
    
    public GetBookletDetailsRequest1(GetBookletDetailsRequest GetBookletDetailsRequest)
    {
        this.GetBookletDetailsRequest = GetBookletDetailsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetBookletDetailsResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wstutorial.com/ws/ChequeDispenseService", Order=0)]
    public GetBookletDetailsResponse GetBookletDetailsResponse;
    
    public GetBookletDetailsResponse1()
    {
    }
    
    public GetBookletDetailsResponse1(GetBookletDetailsResponse GetBookletDetailsResponse)
    {
        this.GetBookletDetailsResponse = GetBookletDetailsResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ChequeDispenseServicePortChannel : ChequeDispenseServicePort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ChequeDispenseServicePortClient : System.ServiceModel.ClientBase<ChequeDispenseServicePort>, ChequeDispenseServicePort
{
    
    public ChequeDispenseServicePortClient()
    {
    }
    
    public ChequeDispenseServicePortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ChequeDispenseServicePortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChequeDispenseServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChequeDispenseServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetTransactionIDResponse1 ChequeDispenseServicePort.GetTransactionID(GetTransactionIDRequest1 request)
    {
        return base.Channel.GetTransactionID(request);
    }
    
    public GetTransactionIDResponse GetTransactionID(GetTransactionIDRequest GetTransactionIDRequest)
    {
        GetTransactionIDRequest1 inValue = new GetTransactionIDRequest1();
        inValue.GetTransactionIDRequest = GetTransactionIDRequest;
        GetTransactionIDResponse1 retVal = ((ChequeDispenseServicePort)(this)).GetTransactionID(inValue);
        return retVal.GetTransactionIDResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetTransactionIDResponse1> ChequeDispenseServicePort.GetTransactionIDAsync(GetTransactionIDRequest1 request)
    {
        return base.Channel.GetTransactionIDAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetTransactionIDResponse1> GetTransactionIDAsync(GetTransactionIDRequest GetTransactionIDRequest)
    {
        GetTransactionIDRequest1 inValue = new GetTransactionIDRequest1();
        inValue.GetTransactionIDRequest = GetTransactionIDRequest;
        return ((ChequeDispenseServicePort)(this)).GetTransactionIDAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PrintedBookletResponse1 ChequeDispenseServicePort.PrintedBooklet(PrintedBookletRequest1 request)
    {
        return base.Channel.PrintedBooklet(request);
    }
    
    public PrintedBookletResponse PrintedBooklet(PrintedBookletRequest PrintedBookletRequest)
    {
        PrintedBookletRequest1 inValue = new PrintedBookletRequest1();
        inValue.PrintedBookletRequest = PrintedBookletRequest;
        PrintedBookletResponse1 retVal = ((ChequeDispenseServicePort)(this)).PrintedBooklet(inValue);
        return retVal.PrintedBookletResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PrintedBookletResponse1> ChequeDispenseServicePort.PrintedBookletAsync(PrintedBookletRequest1 request)
    {
        return base.Channel.PrintedBookletAsync(request);
    }
    
    public System.Threading.Tasks.Task<PrintedBookletResponse1> PrintedBookletAsync(PrintedBookletRequest PrintedBookletRequest)
    {
        PrintedBookletRequest1 inValue = new PrintedBookletRequest1();
        inValue.PrintedBookletRequest = PrintedBookletRequest;
        return ((ChequeDispenseServicePort)(this)).PrintedBookletAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ValidateTransactionIDResponse1 ChequeDispenseServicePort.ValidateTransactionID(ValidateTransactionIDRequest1 request)
    {
        return base.Channel.ValidateTransactionID(request);
    }
    
    public ValidateTransactionIDResponse ValidateTransactionID(ValidateTransactionIDRequest ValidateTransactionIDRequest)
    {
        ValidateTransactionIDRequest1 inValue = new ValidateTransactionIDRequest1();
        inValue.ValidateTransactionIDRequest = ValidateTransactionIDRequest;
        ValidateTransactionIDResponse1 retVal = ((ChequeDispenseServicePort)(this)).ValidateTransactionID(inValue);
        return retVal.ValidateTransactionIDResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ValidateTransactionIDResponse1> ChequeDispenseServicePort.ValidateTransactionIDAsync(ValidateTransactionIDRequest1 request)
    {
        return base.Channel.ValidateTransactionIDAsync(request);
    }
    
    public System.Threading.Tasks.Task<ValidateTransactionIDResponse1> ValidateTransactionIDAsync(ValidateTransactionIDRequest ValidateTransactionIDRequest)
    {
        ValidateTransactionIDRequest1 inValue = new ValidateTransactionIDRequest1();
        inValue.ValidateTransactionIDRequest = ValidateTransactionIDRequest;
        return ((ChequeDispenseServicePort)(this)).ValidateTransactionIDAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetBookletDetailsResponse1 ChequeDispenseServicePort.GetBookletDetails(GetBookletDetailsRequest1 request)
    {
        return base.Channel.GetBookletDetails(request);
    }
    
    public GetBookletDetailsResponse GetBookletDetails(GetBookletDetailsRequest GetBookletDetailsRequest)
    {
        GetBookletDetailsRequest1 inValue = new GetBookletDetailsRequest1();
        inValue.GetBookletDetailsRequest = GetBookletDetailsRequest;
        GetBookletDetailsResponse1 retVal = ((ChequeDispenseServicePort)(this)).GetBookletDetails(inValue);
        return retVal.GetBookletDetailsResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetBookletDetailsResponse1> ChequeDispenseServicePort.GetBookletDetailsAsync(GetBookletDetailsRequest1 request)
    {
        return base.Channel.GetBookletDetailsAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetBookletDetailsResponse1> GetBookletDetailsAsync(GetBookletDetailsRequest GetBookletDetailsRequest)
    {
        GetBookletDetailsRequest1 inValue = new GetBookletDetailsRequest1();
        inValue.GetBookletDetailsRequest = GetBookletDetailsRequest;
        return ((ChequeDispenseServicePort)(this)).GetBookletDetailsAsync(inValue);
    }
}
